### ISSUE TITLE
TypeError: Subscripted generics cannot be used with class and instance checks

### ISSUE THREAD

**Issue by kamadforge** [google-deepmind/jax_privacy#11]
There appears the error given as 

[jaxline] training loop failed with error 

and in more detail, 

TypeError: Subscripted generics cannot be used with class and instance checks

What could be the reason of such error?

**Comment by lberrada** [comment]
I cannot reproduce this error locally, could you detail which versions of python, jax and chex you are using?

**Comment by lberrada** [comment]
Closing due to lack of reproducibility.
